site_name: CG DevX User Guidelines
nav:
    - Home: index.md
    - Getting started: getting_started.md
    - Dashboard User Guide: dashboard_user_guide.md
    - Workload Management: workload_management.md