site_name: CG DevX Guide
nav:
  - 'Home': index.md
  - 'CG DevX':
      - 'Platform Engineering': 'platform_engineering.md'
      - 'Why CG DevX': 'cgdevx.md'
      - 'Concept': 'approach.md'
      - 'Capabilities':
          - 'Capabilities Overview': 'capabilities/capabilities.md'
          - 'Reference Implementation': 'capabilities/reference_implementation.md'
          - 'Shared Responsibility': 'capabilities/known_limitations.md'
      - 'Acknowledgements': 'tools.md'

  - 'Operators Guide':
      - operators_guide/concept.md
      - operators_guide/supported_platforms.md
      - 'Installation':
          - operators_guide/installation/quickstart.md
          - 'CLI':
              - operators_guide/installation/installing_cli.md
              - operators_guide/installation/building_cli.md
              - operators_guide/installation/cli_commands.md
          - 'Cloud':
              - operators_guide/installation/cloud/aws_setup.md
              - operators_guide/installation/cloud/azure_setup.md
          - 'Git':
              - operators_guide/installation/vcs/github_setup.md
              - operators_guide/installation/vcs/gitlab_setup.md
      - 'Platform Management':
          - operators_guide/platform_management/platform_repo.md
          - 'Terraform':
              - operators_guide/platform_management/iac/vcs_management.md
              - operators_guide/platform_management/iac/core_infrastructure_management.md
              - operators_guide/platform_management/iac/secrets_management.md
              - operators_guide/platform_management/iac/users_management.md
              - operators_guide/platform_management/iac/core_services.md
          - 'Services':
              - operators_guide/platform_management/services/delivery.md
              - operators_guide/platform_management/services/integration.md
              - operators_guide/platform_management/services/monitoring.md
              - operators_guide/platform_management/services/registry.md
              - operators_guide/platform_management/services/secrets.md
              - operators_guide/platform_management/services/security.md
      - 'Workload Management':
          - operators_guide/workload_management/workloads.md
          - operators_guide/workload_management/cli_commands.md
          - operators_guide/workload_management/bootstrap_templates.md
          - operators_guide/workload_management/environments.md
      - 'Delivery Pipelines':
          - operators_guide/delivery_pipelines/core_services_delivery.md

  - 'Developers Guide':
      - developers_guide/concept.md
      - 'Workloads':
          - developers_guide/workloads/concept.md
          - developers_guide/workloads/gitops_environments.md
      - 'Pipelines':
          - developers_guide/cd/delivery.md
          - developers_guide/cd/promotion.md
          - developers_guide/ci/integration.md
          - developers_guide/ci/code_quality.md
          - developers_guide/ci/devsecops.md
      - 'Observability':
          - developers_guide/observability/monitoring.md
          - developers_guide/observability/dashboards.md
      - 'Artifacts':
          - developers_guide/artifacts/registry.md
          - developers_guide/artifacts/registry_proxy.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - hcl
    - python
    - bash

plugins:
  - drawio_file
  - search
  - mermaid2

site_author: alexu@cloudgeometry.io
