site_name: CG DevX User Guidelines
nav:
    - Home: index.md
    - Getting started: getting_started.md
    - Dashboard User Guide: dashboard_user_guide.md
    - Workload Management: workload_management.md
    - CGDevX Applications: 
       - ArgoCD: cgdevx_apps/cgdevx_argocd.md
       - Grafana: cgdevx_apps/cgdevx_grafana.md
       - CertManager: cgdevx_apps/cgdevx_certmanager.md